apiVersion: v1
kind: Service
metadata:
  name: website-service
  namespace: nginx
spec:
  type: NodePort
  selector:
    app: my-website
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30080
