apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-deployment
  namespace: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio

    spec:
      containers:
        - name: portfolio-container
          image: chinuvalentine/portfolio-website:1.0
          ports:
            - containerPort: 3000

          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "300m"
