apiVersion: v1
kind: Service
metadata:
  name: addition-service
  namespace: nginx
spec:
  selector:
    app: addition
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort

