apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio
  namespace: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      containers:
        - name: portfolio-container
          image: chinuvalentine/pyapp:latest
          ports:
            - containerPort: 3000
