apiVersion: v1
kind: Service
metadata:
  name: portfolio-service
  namespace: nginx
spec:
  type: NodePort
  selector:
    app: portfolio
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30080
