apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-deployment1
  namespace: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      containers:
        - name: portfolio
          image: chinuvalentine/chinu:latest
          ports:
            - containerPort: 3000

