apiVersion: v1
kind: Service
metadata:
  name: portfolio-service
  namespace: nginx
spec:
  type: NodePort
  selector:
    app: portfolio
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30008

